name: Pipeline

on: push

jobs:
  code-quality:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: ./.github/actions/setup-environment
      - name: Install dependencies
        run: |
          poetry install --with dev --no-interaction --no-root
      - name: Run ruff
        run: |
          poetry run pre-commit run -a 

  test-image-build:
    runs-on: ubuntu-24.04
    needs: code-quality
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: ./.github/actions/setup-environment
      - name: Install dependencies
        run: |
          poetry install --with dev --no-interaction --no-root
      - name: Run tests with pytest
        run: |
          poetry run pytest --cov build --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  publish-image:
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - code-quality
      - test-image-build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Get Git Commit Tag Name
        uses: olegtarasov/get-tag@v2.1.4
      - name: Set up Python environment
        uses: ./.github/actions/setup-environment
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
      - name: Publish Images to Docker Hub
        env:
          STATIC_SITE_CONTAINERIZER_REGISTRY_USERNAME: ${{ secrets.STATIC_SITE_CONTAINERIZER_REGISTRY_USERNAME }}
          STATIC_SITE_CONTAINERIZER_REGISTRY_PASSWORD: ${{ secrets.STATIC_SITE_CONTAINERIZER_REGISTRY_PASSWORD }}
        run: |          
          poetry run static-site-containerizer --content rust-web-rcon --tag pfeiffermax/rust-web-rcon:$GIT_TAG_NAME --platform linux/amd64 --platform linux/arm64 --push
